name: Validate Tags

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - run: docker run -v ./tags:/tags ghcr.io/fabricmc/fabric-discord-bot-tags:latest
